Temp failure

diff --git a/.github/workflows/slack.yml b/.github/workflows/slack.yml
--- a/.github/workflows/slack.yml
+++ b/.github/workflows/slack.yml
@@ -17,13 +17,13 @@ jobs:
         echo 'This is an artifact' >> artifacts/one.txt
     - name: run command
       shell: bash
-      run: sleep 5
+      run: sleep 1
     - name: run command
       shell: bash
       run: |-
         mkdir -p artifacts
         echo 'This is from another build step' >> artifacts/two.txt
-        exit 0
+        exit 1
     - name: slack-notify-on-action-start
       uses: rtCamp/action-slack-notify@v2.2.0
       env:
@@ -31,8 +31,10 @@ jobs:
         SLACK_CHANNEL: "${{ secrets.SLACK_CHANNEL }}"
         SLACK_MESSAGE: Default Custom Message
     - id: last_build_status
+      if: always()
       uses: actions/github-script@v6.3.3
       with:
+        result-encoding: string
         script: |-
           currentWorkflowId = (
             await github.rest.actions.getWorkflowRun({
@@ -50,6 +52,13 @@ jobs:
             per_page: 1
           });
           return runsList.data.workflow_runs[0].conclusion
+    - name: run command
+      if: always()
+      shell: bash
+      run: |-
+        echo '${{ steps.last_build_status.outputs.result }}'
+        echo '${{ steps.last_build_status.outputs.result == 'failure' }}'
+        echo '${{ steps.last_build_status.outputs.result == '"failure"' }}'
     - uses: rtCamp/action-slack-notify@v2.2.0
       if: success()
       env:
@@ -58,11 +67,11 @@ jobs:
         SLACK_MESSAGE: Custom Success Message
         SLACK_COLOR: success
     - uses: rtCamp/action-slack-notify@v2.2.0
-      if: failure() && steps.last_build_status.outputs.result == 'success'
+      if: failure() && steps.last_build_status.outputs.result == 'failure'
       env:
         SLACK_WEBHOOK: "${{ secrets.SLACK_WEBHOOK }}"
         SLACK_CHANNEL: "${{ secrets.SLACK_CHANNEL }}"
-        SLACK_MESSAGE: 'Custom Failure Message :sad:'
+        SLACK_MESSAGE: 'Repeated failure :cry:'
         SLACK_COLOR: failure
     - uses: rtCamp/action-slack-notify@v2.2.0
       if: cancelled()
